"""Shared authority loader for gpu_cfd foundation tooling."""

from .acceptance import (
    AcceptanceClassResult,
    AcceptanceEvaluationContext,
    AcceptanceVerdict,
    AcceptanceWaiver,
    AcceptanceWaiverHook,
    AcceptedTupleResolution,
    evaluate_acceptance,
    resolve_accepted_tuple,
)
from .bundle import (
    AuthorityBundle,
    AuthorityConflictError,
    AuthorityLoadError,
    AuthorityLoadReport,
    AuthoritySchemaError,
    load_authority_bundle,
    main,
    repo_root,
)
from .pins import (
    ConsumerPinResolution,
    EmittedEnvironmentManifests,
    emit_environment_manifests,
    resolve_consumer_pin_manifest,
)
from .support_scanner import (
    SupportBoundaryCondition,
    SupportFunctionObject,
    SupportScanIssue,
    SupportScanRejected,
    SupportScanRequest,
    SupportScanReport,
    SupportStartupSeedFieldValue,
    SupportStartupSeedRegion,
    SupportStartupSeedSpec,
    enforce_support_scan,
    scan_support_matrix,
)

__all__ = [
    "AcceptanceClassResult",
    "AcceptanceEvaluationContext",
    "AcceptanceVerdict",
    "AcceptanceWaiver",
    "AcceptanceWaiverHook",
    "AcceptedTupleResolution",
    "AuthorityBundle",
    "AuthorityConflictError",
    "AuthorityLoadError",
    "AuthorityLoadReport",
    "AuthoritySchemaError",
    "ConsumerPinResolution",
    "EmittedEnvironmentManifests",
    "SupportBoundaryCondition",
    "SupportFunctionObject",
    "SupportScanIssue",
    "SupportScanRejected",
    "SupportScanRequest",
    "SupportScanReport",
    "SupportStartupSeedFieldValue",
    "SupportStartupSeedRegion",
    "SupportStartupSeedSpec",
    "emit_environment_manifests",
    "enforce_support_scan",
    "evaluate_acceptance",
    "load_authority_bundle",
    "main",
    "repo_root",
    "resolve_accepted_tuple",
    "resolve_consumer_pin_manifest",
    "scan_support_matrix",
]
